# Generated by Django 3.2.16 on 2025-07-26 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0004_congratulation'),
    ]

    operations = [
        migrations.AddField(
            model_name='congratulation',
            name='text',
            field=models.TextField(default=1024, verbose_name='Текст поздравления'),
            preserve_default=False,
        ),
    ]
